modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="oblivioustweaks" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Oblivious Tweaks" #mandatory
displayURL="https://obliviousreality.github.io/oblivioustweaks.html" #optional
logoFile="examplemod.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Programming by TsarOblivious, Textures by British_Nerd" #optional
description='''
A Slightly Oblivious set of Tweaks for Minecraft.
'''
[[dependencies.oblivioustweaks]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.oblivioustweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
